spring:
  application:
    name: product-service
  datasource:
    username: root
    password: root
    url: "jdbc:mysql://localhost:3306/product_db"
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer:
server:
  port: 8888
